services:
  - type: web
    name: icetask3
    env: node
    rootDir: IceTask3
    buildCommand: npm install && npm run build
    startCommand: npm run start
    repo: https://github.com/yourusername/yourrepo
    branch: main
    plan: free